// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htezgbnwooldbbtsbswz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0ZXpnYm53b29sZGJidHNic3d6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNzA1MTEsImV4cCI6MjA2Njk0NjUxMX0.q6O2U2mSCsuYnXwtMKEDiQkUpicPcrHP15JPcn1tbis";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});